# Generated by Django 5.0.4 on 2024-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='deriction_production',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='address', to='accounts.cities'),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='list_pick_up_point',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_pick_up_point', to='accounts.cities'),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='list_warehouse',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_warehouse', to='accounts.cities'),
        ),
    ]
