# Generated by Django 5.0.4 on 2024-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cities_accountsmodel_deriction_production_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsmodel',
            old_name='deriction_production',
            new_name='production',
        ),
    ]
