# Generated by Django 5.0.4 on 2024-04-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_deriction_production_accountsmodel_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='address', to='accounts.cities'),
        ),
        migrations.AlterField(
            model_name='accountsmodel',
            name='list_pick_up_point',
            field=models.ManyToManyField(blank=True, related_name='list_pick_up_point', to='accounts.cities'),
        ),
        migrations.AlterField(
            model_name='accountsmodel',
            name='list_warehouse',
            field=models.ManyToManyField(blank=True, related_name='list_warehouse', to='accounts.cities'),
        ),
    ]
