# Generated by Django 5.0.4 on 2024-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountsmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
