# Generated by Django 5.0.4 on 2024-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountsmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
