# Generated by Django 5.0.4 on 2024-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usercartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartmodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.ordermodel'),
        ),
    ]
