# Generated by Django 5.0.4 on 2024-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usercartmodel_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercartmodel',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
