# Generated by Django 5.0.4 on 2024-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cities_options'),
        ('main', '0005_alter_usercartmodel_options_ordermodel_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='warehouse',
            field=models.ManyToManyField(related_name='warehouse_order', to='accounts.cities'),
        ),
    ]
