# Generated by Django 5.0.4 on 2024-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ordermodel_description_alter_ordermodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
