# Generated by Django 5.0.4 on 2024-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_ordermodel_picture1_alter_ordermodel_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delevery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
